USE d_tennis;
INSERT location (id_location, libelle_localisation) VALUES (1, N'Houston');
INSERT location (id_location, libelle_localisation) VALUES (2, N'Estoril');
INSERT location (id_location, libelle_localisation) VALUES (3, N'Rome');
INSERT location (id_location, libelle_localisation) VALUES (4, N'Hamburg');
INSERT location (id_location, libelle_localisation) VALUES (5, N'St. Polten');
INSERT location (id_location, libelle_localisation) VALUES (6, N'Paris');
INSERT location (id_location, libelle_localisation) VALUES (7, N'Halle');
INSERT location (id_location, libelle_localisation) VALUES (8, N'Queens Club');
INSERT location (id_location, libelle_localisation) VALUES (9, N'Nottingham');
INSERT location (id_location, libelle_localisation) VALUES (10, N'London');
INSERT location (id_location, libelle_localisation) VALUES (11, N'Bastad');
INSERT location (id_location, libelle_localisation) VALUES (12, N'Newport');
INSERT location (id_location, libelle_localisation) VALUES (13, N'Indianapolis');
INSERT location (id_location, libelle_localisation) VALUES (14, N'Stuttgart');
INSERT location (id_location, libelle_localisation) VALUES (15, N'Kitzbuhel');
INSERT location (id_location, libelle_localisation) VALUES (16, N'Umag');
INSERT location (id_location, libelle_localisation) VALUES (17, N'Adelaide');
INSERT location (id_location, libelle_localisation) VALUES (18, N'Chennai');
INSERT location (id_location, libelle_localisation) VALUES (19, N'Doha');
INSERT location (id_location, libelle_localisation) VALUES (20, N'Auckland');
INSERT location (id_location, libelle_localisation) VALUES (21, N'Sydney');
INSERT location (id_location, libelle_localisation) VALUES (22, N'Melbourne');
INSERT location (id_location, libelle_localisation) VALUES (23, N'Bogota');
INSERT location (id_location, libelle_localisation) VALUES (24, N'Marseille');
INSERT location (id_location, libelle_localisation) VALUES (25, N'Vina del Mar');
INSERT location (id_location, libelle_localisation) VALUES (26, N'Buenos Aires');
INSERT location (id_location, libelle_localisation) VALUES (27, N'Memphis');
INSERT location (id_location, libelle_localisation) VALUES (28, N'Barcelona');
INSERT location (id_location, libelle_localisation) VALUES (29, N's-Hertogenbosch');
INSERT location (id_location, libelle_localisation) VALUES (30, N'Gstaad');
INSERT location (id_location, libelle_localisation) VALUES (31, N'Amsterdam');
INSERT location (id_location, libelle_localisation) VALUES (32, N'Montreal');
INSERT location (id_location, libelle_localisation) VALUES (33, N'Cincinnati');
INSERT location (id_location, libelle_localisation) VALUES (34, N'Washington');
INSERT location (id_location, libelle_localisation) VALUES (35, N'Long Island');
INSERT location (id_location, libelle_localisation) VALUES (36, N'New York');
INSERT location (id_location, libelle_localisation) VALUES (37, N'Delray Beach');
INSERT location (id_location, libelle_localisation) VALUES (38, N'Costa Do Sauipe');
INSERT location (id_location, libelle_localisation) VALUES (39, N'San Jose');
INSERT location (id_location, libelle_localisation) VALUES (40, N'Rotterdam');
INSERT location (id_location, libelle_localisation) VALUES (41, N'Dubai');
INSERT location (id_location, libelle_localisation) VALUES (42, N'Las Vegas');
INSERT location (id_location, libelle_localisation) VALUES (43, N'Valencia');
INSERT location (id_location, libelle_localisation) VALUES (44, N'Monte Carlo');
INSERT location (id_location, libelle_localisation) VALUES (45, N'Portschach');
INSERT location (id_location, libelle_localisation) VALUES (46, N'Los Angeles');
INSERT location (id_location, libelle_localisation) VALUES (47, N'Sopot');
INSERT location (id_location, libelle_localisation) VALUES (48, N'New Haven');
INSERT location (id_location, libelle_localisation) VALUES (49, N'Beijing');
INSERT location (id_location, libelle_localisation) VALUES (50, N'Bucharest');
INSERT location (id_location, libelle_localisation) VALUES (51, N'Bangkok');
INSERT location (id_location, libelle_localisation) VALUES (52, N'Tokyo');
INSERT location (id_location, libelle_localisation) VALUES (53, N'Stockholm');
INSERT location (id_location, libelle_localisation) VALUES (54, N'Madrid');
INSERT location (id_location, libelle_localisation) VALUES (55, N'Lyon');
INSERT location (id_location, libelle_localisation) VALUES (56, N'St. Petersburg');
INSERT location (id_location, libelle_localisation) VALUES (57, N'Acapulco');
INSERT location (id_location, libelle_localisation) VALUES (58, N'Indian Wells');
INSERT location (id_location, libelle_localisation) VALUES (59, N'Miami');
INSERT location (id_location, libelle_localisation) VALUES (60, N'Brisbane');
INSERT location (id_location, libelle_localisation) VALUES (61, N'Montpellier');
INSERT location (id_location, libelle_localisation) VALUES (62, N'Quito');
INSERT location (id_location, libelle_localisation) VALUES (63, N'Rio de Janeiro');
INSERT location (id_location, libelle_localisation) VALUES (64, N'Istanbul');
INSERT location (id_location, libelle_localisation) VALUES (65, N'Geneva');
INSERT location (id_location, libelle_localisation) VALUES (66, N'Nice');
INSERT location (id_location, libelle_localisation) VALUES (67, N'Toronto');
INSERT location (id_location, libelle_localisation) VALUES (68, N'Los Cabos');
INSERT location (id_location, libelle_localisation) VALUES (69, N'Sao Paulo');
INSERT location (id_location, libelle_localisation) VALUES (70, N'Casablanca');
INSERT location (id_location, libelle_localisation) VALUES (71, N'Dusseldorf');
INSERT location (id_location, libelle_localisation) VALUES (72, N'Eastbourne');
INSERT location (id_location, libelle_localisation) VALUES (73, N'Atlanta');
INSERT location (id_location, libelle_localisation) VALUES (74, N'Zagreb');
INSERT location (id_location, libelle_localisation) VALUES (75, N'Winston-Salem');
INSERT location (id_location, libelle_localisation) VALUES (76, N'Kuala Lumpur');
INSERT location (id_location, libelle_localisation) VALUES (77, N'Shanghai');
INSERT location (id_location, libelle_localisation) VALUES (78, N'Moscow');
INSERT location (id_location, libelle_localisation) VALUES (79, N'Belgrade');
INSERT location (id_location, libelle_localisation) VALUES (80, N'Munich');
INSERT location (id_location, libelle_localisation) VALUES (81, N'Metz');
INSERT location (id_location, libelle_localisation) VALUES (82, N'Vienna');
INSERT location (id_location, libelle_localisation) VALUES (83, N'Basel');
INSERT location (id_location, libelle_localisation) VALUES (84, N'Oeiras');
INSERT location (id_location, libelle_localisation) VALUES (85, N'Shenzhen');
INSERT location (id_location, libelle_localisation) VALUES (86, N'Milan');
INSERT location (id_location, libelle_localisation) VALUES (87, N'Scottsdale');
INSERT location (id_location, libelle_localisation) VALUES (88, N'Amersfoort');
INSERT location (id_location, libelle_localisation) VALUES (89, N'Palermo');
INSERT location (id_location, libelle_localisation) VALUES (90, N'Chengdu');
INSERT location (id_location, libelle_localisation) VALUES (91, N'Sofia');
INSERT location (id_location, libelle_localisation) VALUES (92, N'Marrakech');
INSERT location (id_location, libelle_localisation) VALUES (93, N'Antwerp');
INSERT location (id_location, libelle_localisation) VALUES (94, N'Johannesburg');
INSERT location (id_location, libelle_localisation) VALUES (95, N'Warsaw');
INSERT location (id_location, libelle_localisation) VALUES (96, N'Copenhagen');
INSERT location (id_location, libelle_localisation) VALUES (97, N'Mallorca');
INSERT location (id_location, libelle_localisation) VALUES (98, N'Salvador');
INSERT location (id_location, libelle_localisation) VALUES (99, N'Mumbai');
INSERT location (id_location, libelle_localisation) VALUES (100, N'Tashkent');
INSERT location (id_location, libelle_localisation) VALUES (101, N'Hong Kong');
INSERT location (id_location, libelle_localisation) VALUES (102, N'Santiago');
INSERT location (id_location, libelle_localisation) VALUES (103, N'Ho Chi Min City');
INSERT location (id_location, libelle_localisation) VALUES (104, N'Brussels');
INSERT location (id_location, libelle_localisation) VALUES (105, N'Birmingham');
INSERT location (id_location, libelle_localisation) VALUES (106, N'Baku');
INSERT location (id_location, libelle_localisation) VALUES (107, N'Quebec');
INSERT location (id_location, libelle_localisation) VALUES (108, N'Seoul');
INSERT location (id_location, libelle_localisation) VALUES (109, N'Linz');
INSERT location (id_location, libelle_localisation) VALUES (110, N'Luxembourg');
INSERT location (id_location, libelle_localisation) VALUES (111, N'Bali');
INSERT location (id_location, libelle_localisation) VALUES (112, N'Strasbourg');
INSERT location (id_location, libelle_localisation) VALUES (113, N'Budapest');
INSERT location (id_location, libelle_localisation) VALUES (114, N'Prague');
INSERT location (id_location, libelle_localisation) VALUES (115, N'Bad Gastein');
INSERT location (id_location, libelle_localisation) VALUES (116, N'Portoroz');
INSERT location (id_location, libelle_localisation) VALUES (117, N'San Diego');
INSERT location (id_location, libelle_localisation) VALUES (118, N'Hobart');
INSERT location (id_location, libelle_localisation) VALUES (119, N'Stanford');
INSERT location (id_location, libelle_localisation) VALUES (120, N'Carlsbad');
INSERT location (id_location, libelle_localisation) VALUES (121, N'Dallas');
INSERT location (id_location, libelle_localisation) VALUES (122, N'Guangzhou');
INSERT location (id_location, libelle_localisation) VALUES (123, N'Pattaya');
INSERT location (id_location, libelle_localisation) VALUES (124, N'Charleston');
INSERT location (id_location, libelle_localisation) VALUES (125, N'Osaka');
INSERT location (id_location, libelle_localisation) VALUES (126, N'Fes');
INSERT location (id_location, libelle_localisation) VALUES (127, N'Marbella');
INSERT location (id_location, libelle_localisation) VALUES (128, N'Monterrey');
INSERT location (id_location, libelle_localisation) VALUES (129, N'Ponte Vedra Beach');
INSERT location (id_location, libelle_localisation) VALUES (130, N'Florianopolis');
INSERT location (id_location, libelle_localisation) VALUES (131, N'Katowice');
INSERT location (id_location, libelle_localisation) VALUES (132, N'Wuhan');
INSERT location (id_location, libelle_localisation) VALUES (133, N'Tianjin');
INSERT location (id_location, libelle_localisation) VALUES (134, N'Bangalore');
INSERT location (id_location, libelle_localisation) VALUES (135, N'Marrakesh');
INSERT location (id_location, libelle_localisation) VALUES (136, N'Zhuhai');
INSERT location (id_location, libelle_localisation) VALUES (137, N'Nürnberg');
INSERT location (id_location, libelle_localisation) VALUES (138, N'College Park');
INSERT location (id_location, libelle_localisation) VALUES (139, N'Nanchang');
INSERT location (id_location, libelle_localisation) VALUES (140, N'Kaohsiung');
INSERT location (id_location, libelle_localisation) VALUES (141, N'Singapore');
INSERT location (id_location, libelle_localisation) VALUES (142, N'Gold Coast');
INSERT location (id_location, libelle_localisation) VALUES (143, N'Zurich');
INSERT location (id_location, libelle_localisation) VALUES (144, N'Berlin');
INSERT location (id_location, libelle_localisation) VALUES (145, N'Kolkata');
INSERT location (id_location, libelle_localisation) VALUES (146, N'Nurnberg');
INSERT location (id_location, libelle_localisation) VALUES (147, N'Rabat');
INSERT location (id_location, libelle_localisation) VALUES (148, N'Monreal');
INSERT location (id_location, libelle_localisation) VALUES (149, N'Amelia Island');
INSERT location (id_location, libelle_localisation) VALUES (150, N'Rogers Cup');
INSERT location (id_location, libelle_localisation) VALUES (151, N'Forest Hills');