INSERT tournament (id, name, type_genre) VALUES (1, N'U.S. Men''s Clay Court Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (2, N'Estoril Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (3, N'Telecom Italia Masters Roma', NULL);
INSERT tournament (id, name, type_genre) VALUES (4, N'Hamburg TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (5, N'Internationaler Raiffeisen Grand Prix', NULL);
INSERT tournament (id, name, type_genre) VALUES (6, N'French Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (7, N'Gerry Weber Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (8, N'Stella Artois', NULL);
INSERT tournament (id, name, type_genre) VALUES (9, N'Nottingham Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (10, N'Wimbledon', NULL);
INSERT tournament (id, name, type_genre) VALUES (11, N'Swedish Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (12, N'Hall of Fame Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (13, N'RCA Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (14, N'Mercedes Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (15, N'Generali Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (16, N'Croatia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (17, N'AAPT Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (18, N'TATA Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (19, N'Qatar Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (20, N'Heineken Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (21, N'adidas International', NULL);
INSERT tournament (id, name, type_genre) VALUES (22, N'Australian Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (23, N'Colombia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (24, N'Marseille Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (25, N'Bellsouth Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (26, N'Copa AT&T', NULL);
INSERT tournament (id, name, type_genre) VALUES (27, N'Kroger St. Jude', NULL);
INSERT tournament (id, name, type_genre) VALUES (28, N'Open Seat Godo', NULL);
INSERT tournament (id, name, type_genre) VALUES (29, N'Rome TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (30, N'Heineken Trophy', NULL);
INSERT tournament (id, name, type_genre) VALUES (31, N'Gstaad Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (32, N'Dutch Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (33, N'Montreal TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (34, N'Cincinnati TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (35, N'Legg Mason Classic', NULL);
INSERT tournament (id, name, type_genre) VALUES (36, N'Hamlet Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (37, N'US Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (38, N'International Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (39, N'Brasil Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (40, N'Open 13', NULL);
INSERT tournament (id, name, type_genre) VALUES (41, N'SAP Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (42, N'Copa Telmex', NULL);
INSERT tournament (id, name, type_genre) VALUES (43, N'Regions Morgan Keegan Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (44, N'ABN AMRO World Tennis Tournament', NULL);
INSERT tournament (id, name, type_genre) VALUES (45, N'Dubai Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (46, N'Channel Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (47, N'Open de Tenis Comunidad Valenciana', NULL);
INSERT tournament (id, name, type_genre) VALUES (48, N'Monte Carlo Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (49, N'Internazionali BNL d''Italia', NULL);
INSERT tournament (id, name, type_genre) VALUES (50, N'Hypo Group Tennis International', NULL);
INSERT tournament (id, name, type_genre) VALUES (51, N'Ordina Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (52, N'The Nottingham Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (53, N'Catella Swedish Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (54, N'Allianz Suisse Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (55, N'Countrywide Classic', NULL);
INSERT tournament (id, name, type_genre) VALUES (56, N'Indianapolis Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (57, N'Idea Prokom Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (58, N'Rogers Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (59, N'Western & Southern Financial Group Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (60, N'Pilot Pen Tennis', NULL);
INSERT tournament (id, name, type_genre) VALUES (61, N'China Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (62, N'Open Romania', NULL);
INSERT tournament (id, name, type_genre) VALUES (63, N'Thailand Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (64, N'AIG Japan Open Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (65, N'Stockholm Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (66, N'Madrid Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (67, N'Grand Prix de Lyon', NULL);
INSERT tournament (id, name, type_genre) VALUES (68, N'St. Petersburg Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (69, N'BNP Paribas', NULL);
INSERT tournament (id, name, type_genre) VALUES (70, N'Abierto Mexicano', NULL);
INSERT tournament (id, name, type_genre) VALUES (71, N'Pacific Life Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (72, N'Sony Ericsson Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (73, N'Brisbane International', NULL);
INSERT tournament (id, name, type_genre) VALUES (74, N'Qatar Exxon Mobil Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (75, N'ASB Classic', NULL);
INSERT tournament (id, name, type_genre) VALUES (76, N'Apia International', NULL);
INSERT tournament (id, name, type_genre) VALUES (77, N'Open Sud de France', NULL);
INSERT tournament (id, name, type_genre) VALUES (78, N'Ecuador Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (79, N'Argentina Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (80, N'Memphis Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (81, N'Rio Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (82, N'BNP Paribas Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (83, N'Open Banco Sabadell', NULL);
INSERT tournament (id, name, type_genre) VALUES (84, N'BRD Nastase Tiriac Trophy', NULL);
INSERT tournament (id, name, type_genre) VALUES (85, N'Millenium Estoril Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (86, N'Istanbul Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (87, N'Mutua Madrid Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (88, N'Geneva Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (89, N'Open de Nice Côte d’Azur', NULL);
INSERT tournament (id, name, type_genre) VALUES (90, N'Topshelf Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (91, N'AEGON Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (92, N'SkiStar Swedish Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (93, N'German Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (94, N'Suisse Open Gstaad', NULL);
INSERT tournament (id, name, type_genre) VALUES (95, N'Konzum Croatia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (96, N'Citi Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (97, N'Abierto Mexicano Mifel', NULL);
INSERT tournament (id, name, type_genre) VALUES (98, N'AEGON Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (99, N'Grand Prix Hassan II', NULL);
INSERT tournament (id, name, type_genre) VALUES (100, N'Dusseldorf Open', NULL);

INSERT tournament (id, name, type_genre) VALUES (101, N'Mutua Madrileña Madrid Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (102, N'AEGON International', NULL);
INSERT tournament (id, name, type_genre) VALUES (103, N'Unicef Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (104, N'Atlanta Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (105, N'German Open Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (106, N'Studena Croatia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (107, N'Bet-At-Home Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (108, N'Chennai Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (109, N'Medibank International', NULL);
INSERT tournament (id, name, type_genre) VALUES (110, N'PBZ Zagreb Indoors', NULL);
INSERT tournament (id, name, type_genre) VALUES (111, N'Copa Claro', NULL);
INSERT tournament (id, name, type_genre) VALUES (112, N'Winston-Salem Open at Wake Forest University', NULL);
INSERT tournament (id, name, type_genre) VALUES (113, N'Malaysian Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (114, N'Rakuten Japan Open Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (115, N'Shanghai Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (116, N'Kremlin Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (117, N'Serbia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (118, N'BMW Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (119, N'Crédit Agricole Suisse Open Gstaad', NULL);
INSERT tournament (id, name, type_genre) VALUES (120, N'Farmers Classic', NULL);
INSERT tournament (id, name, type_genre) VALUES (121, N'Open de Moselle', NULL);
INSERT tournament (id, name, type_genre) VALUES (122, N'Erste Bank Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (123, N'Swiss Indoors', NULL);
INSERT tournament (id, name, type_genre) VALUES (124, N'Valencia Open 500', NULL);
INSERT tournament (id, name, type_genre) VALUES (125, N'BNP Paribas Masters', NULL);
INSERT tournament (id, name, type_genre) VALUES (126, N'Masters Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (127, N'Delray Beach Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (128, N'Portugal Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (129, N'Claro Open Colombia', NULL);
INSERT tournament (id, name, type_genre) VALUES (130, N'bet-at-home Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (131, N'BB&T Atlanta Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (132, N'ATP Vegeta Croatia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (133, N'Shenzhen Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (134, N'Royal Guard Open Chile', NULL);
INSERT tournament (id, name, type_genre) VALUES (135, N'Next Generation Hardcourts', NULL);
INSERT tournament (id, name, type_genre) VALUES (136, N'Internazionali di Lombardia', NULL);
INSERT tournament (id, name, type_genre) VALUES (137, N'ATP Buenos Aires 2005', NULL);
INSERT tournament (id, name, type_genre) VALUES (138, N'Dubai Duty Free Men''s Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (139, N'NASDAQ-100 Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (140, N'Red Letter Days Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (141, N'Synsam Swedish Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (142, N'Campionati Internazionali Di Sicilia', NULL);
INSERT tournament (id, name, type_genre) VALUES (143, N'Japan Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (144, N'BA-CA Tennis Trophy', NULL);
INSERT tournament (id, name, type_genre) VALUES (145, N'Davidoff Swiss Indoors', NULL);
INSERT tournament (id, name, type_genre) VALUES (146, N'Chengdu Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (147, N'Garanti Koza Sofia Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (148, N'Dubai Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (149, N'CAM Open Comunidad Valenciana', NULL);
INSERT tournament (id, name, type_genre) VALUES (150, N'European Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (151, N'U.S. National Indoor Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (152, N'VTR Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (153, N'SA Tennis Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (154, N'Movistar Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (155, N'International German Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (156, N'LA Tennis Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (157, N'Next Generation Adelaide International', NULL);
INSERT tournament (id, name, type_genre) VALUES (158, N'Austrian Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (159, N'Open Sabadell Atlántico 2008', NULL);
INSERT tournament (id, name, type_genre) VALUES (160, N'Orange Prokom Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (161, N'Sydney International', NULL);
INSERT tournament (id, name, type_genre) VALUES (162, N'Campionati Internazional d''Italia', NULL);
INSERT tournament (id, name, type_genre) VALUES (163, N'Breil ATP', NULL);
INSERT tournament (id, name, type_genre) VALUES (164, N'Siebel Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (165, N'Copenhagen Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (166, N'Franklin Templeton Tennis Classic', NULL);
INSERT tournament (id, name, type_genre) VALUES (167, N'Sybase Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (168, N'Citrix Tennis Championships', NULL);
INSERT tournament (id, name, type_genre) VALUES (169, N'Mallorca Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (170, N'Ericsson Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (171, N'Mercedes-Benz Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (172, N'Milan Indoors', NULL);
INSERT tournament (id, name, type_genre) VALUES (173, N'Toronto TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (174, N'Kingfisher Airlines Tennis Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (175, N'TD Waterhouse Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (176, N'Priority Telecom Dutch Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (177, N'ATP Buenos Aires 2004', NULL);
INSERT tournament (id, name, type_genre) VALUES (178, N'Gelsor Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (179, N'President''s Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (180, N'Salem Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (181, N'CA Tennis Trophy', NULL);
INSERT tournament (id, name, type_genre) VALUES (182, N'Stuttgart TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (183, N'Indian Wells TMS', NULL);
INSERT tournament (id, name, type_genre) VALUES (184, N'Verizon Tennis Challenge', NULL);
INSERT tournament (id, name, type_genre) VALUES (185, N'Indesit ATP Milano Indoor', NULL);
INSERT tournament (id, name, type_genre) VALUES (186, N'Rogers Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (187, N'Power Horse Cup', NULL);
INSERT tournament (id, name, type_genre) VALUES (188, N'Proton Malaysian Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (189, N'Slazenger Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (190, N'Queens Club', NULL);
INSERT tournament (id, name, type_genre) VALUES (191, N'Energis Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (192, N'Vietnam Open', NULL);
INSERT tournament (id, name, type_genre) VALUES (193, N'Brussels Open', 2);
INSERT tournament (id, name, type_genre) VALUES (194, N'AEGON Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (195, N'Baku Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (196, N'Western & Southern Financial Group Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (197, N'New Haven Open at Yale', 2);
INSERT tournament (id, name, type_genre) VALUES (198, N'Bell Challenge', 2);
INSERT tournament (id, name, type_genre) VALUES (199, N'Hansol Korea Open', 2);
INSERT tournament (id, name, type_genre) VALUES (200, N'Toray Pan Pacific Open', 2);

INSERT tournament (id, name, type_genre) VALUES (201, N'Generali Ladies Linz', 2);
INSERT tournament (id, name, type_genre) VALUES (202, N'BGL BNP Paribas Luxembourg Open', 2);
INSERT tournament (id, name, type_genre) VALUES (203, N'Sony Ericsson Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (204, N'Commonwealth Bank Tournament of Champions', 2);
INSERT tournament (id, name, type_genre) VALUES (205, N'Internationaux de Strasbourg', 2);
INSERT tournament (id, name, type_genre) VALUES (206, N'Gaz de France Budapest Grand Prix', 2);
INSERT tournament (id, name, type_genre) VALUES (207, N'ECM Prague Open', 2);
INSERT tournament (id, name, type_genre) VALUES (208, N'Gastein Ladies', 2);
INSERT tournament (id, name, type_genre) VALUES (209, N'Banka Koper Slovenia Open', 2);
INSERT tournament (id, name, type_genre) VALUES (210, N'Istanbul Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (211, N'e-Boks Sony Ericsson Open', 2);
INSERT tournament (id, name, type_genre) VALUES (212, N'Mercury Insurance Open', 2);
INSERT tournament (id, name, type_genre) VALUES (213, N'Moorilla Hobart International', 2);
INSERT tournament (id, name, type_genre) VALUES (214, N'Italiacom Open', 2);
INSERT tournament (id, name, type_genre) VALUES (215, N'Bank of the West Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (216, N'Texas Tennis Open', 2);
INSERT tournament (id, name, type_genre) VALUES (217, N'Tashkent Open', 2);
INSERT tournament (id, name, type_genre) VALUES (218, N'GRC Bank Guangzhou International Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (219, N'KDB Korea Open', 2);
INSERT tournament (id, name, type_genre) VALUES (220, N'Apai International', 2);
INSERT tournament (id, name, type_genre) VALUES (221, N'Open Gaz de France', 2);
INSERT tournament (id, name, type_genre) VALUES (222, N'Pattaya Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (223, N'Copa BBVA Colsanitas', 2);
INSERT tournament (id, name, type_genre) VALUES (224, N'Qatar Total Open', 2);
INSERT tournament (id, name, type_genre) VALUES (225, N'Dubai Duty Free Tennis Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (226, N'Memphis International', 2);
INSERT tournament (id, name, type_genre) VALUES (227, N'Malaysia Open', 2);
INSERT tournament (id, name, type_genre) VALUES (228, N'Family Circle Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (229, N'HP Open', 2);
INSERT tournament (id, name, type_genre) VALUES (230, N'Qatar Airways Tournament of Champions Sofia', 2);
INSERT tournament (id, name, type_genre) VALUES (231, N'Grand Prix de SAR La Princesse Lalla Meryem', 2);
INSERT tournament (id, name, type_genre) VALUES (232, N'Budapest Grand Prix', 2);
INSERT tournament (id, name, type_genre) VALUES (233, N'Cellular South Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (234, N'Andalucia Tennis Experience', 2);
INSERT tournament (id, name, type_genre) VALUES (235, N'Monterrey Open', 2);
INSERT tournament (id, name, type_genre) VALUES (236, N'Barcelona Ladies Open', 2);
INSERT tournament (id, name, type_genre) VALUES (237, N'Barclays Dubai Tennis Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (239, N'Internazionali Femminili di Tennis di Palermo', 2);
INSERT tournament (id, name, type_genre) VALUES (241, N'FORTIS Championships Luxembourg', 2);
INSERT tournament (id, name, type_genre) VALUES (242, N'MPS Group Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (243, N'Porsche Tennis Grand Prix', 2);
INSERT tournament (id, name, type_genre) VALUES (244, N'Sony Swedish Open', 2);
INSERT tournament (id, name, type_genre) VALUES (245, N'US National Indoor Tennis Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (246, N'Brasil Tennis Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (247, N'BNP Paribas Katowice Open', 2);
INSERT tournament (id, name, type_genre) VALUES (248, N'Copa Claro Colsanitas', 2);
INSERT tournament (id, name, type_genre) VALUES (249, N'Collector Swedish Open', 2);
INSERT tournament (id, name, type_genre) VALUES (250, N'Connecticut Open', 2);
INSERT tournament (id, name, type_genre) VALUES (251, N'Coupe Banque Nationale', 2);
INSERT tournament (id, name, type_genre) VALUES (252, N'Japan Women''s Tennis Open', 2);
INSERT tournament (id, name, type_genre) VALUES (253, N'Guangzhou Open', 2);
INSERT tournament (id, name, type_genre) VALUES (254, N'Kia Korea Open', 2);
INSERT tournament (id, name, type_genre) VALUES (255, N'Wuhan Open', 2);
INSERT tournament (id, name, type_genre) VALUES (256, N'Tianjin Open', 2);
INSERT tournament (id, name, type_genre) VALUES (257, N'Hobart International', 2);
INSERT tournament (id, name, type_genre) VALUES (258, N'Open GDF Suez', 2);
INSERT tournament (id, name, type_genre) VALUES (259, N'International Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (260, N'Nordea Nordic Light Open', 2);
INSERT tournament (id, name, type_genre) VALUES (261, N'Commonwealth Bank Tennis Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (263, N'Copa Sony Ericsson Colsanitas', 2);
INSERT tournament (id, name, type_genre) VALUES (264, N'Warsaw Open', 2);
INSERT tournament (id, name, type_genre) VALUES (265, N'LA Womens Tennis Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (266, N'Proximus Diamond Games', 2);
INSERT tournament (id, name, type_genre) VALUES (267, N'Sony Ericsson International', 2);
INSERT tournament (id, name, type_genre) VALUES (268, N'Dubai Duty Free Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (269, N'Shenzhen Longgang Gemdale Open', 2);
INSERT tournament (id, name, type_genre) VALUES (270, N'BNP Paribas Fortis Diamond Games', 2);
INSERT tournament (id, name, type_genre) VALUES (271, N'Katowice Open', 2);
INSERT tournament (id, name, type_genre) VALUES (272, N'Grand Prix SAR Lalla Meryem', 2);
INSERT tournament (id, name, type_genre) VALUES (273, N'J&T Banka Prague Open', 2);
INSERT tournament (id, name, type_genre) VALUES (274, N'Bucharest Open', 2);
INSERT tournament (id, name, type_genre) VALUES (275, N'TEB BNP Paribas Istanbul Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (276, N'Prudential Hong Kong Tennis Open', 2);
INSERT tournament (id, name, type_genre) VALUES (277, N'WTA Elite Trophy', 2);
INSERT tournament (id, name, type_genre) VALUES (278, N'Nürnberger Versicherungscup', 2);
INSERT tournament (id, name, type_genre) VALUES (279, N'POLI-FARBE Budapest Grand Prix', 2);
INSERT tournament (id, name, type_genre) VALUES (280, N'WANLIMA Guangzhou International Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (281, N'Qatar Ladies Open', 2);
INSERT tournament (id, name, type_genre) VALUES (282, N'Jiangxi Women''s Tennis Open', 2);
INSERT tournament (id, name, type_genre) VALUES (283, N'Ladies Trophy', 2);
INSERT tournament (id, name, type_genre) VALUES (284, N'Taiwan Open', 2);
INSERT tournament (id, name, type_genre) VALUES (285, N'BNP Paribas WTA Finals', 2);
INSERT tournament (id, name, type_genre) VALUES (286, N'GDD-Guangzhou International Womens Open', 2);
INSERT tournament (id, name, type_genre) VALUES (287, N'Mondial Australian Women''s Hardcourts', 2);
INSERT tournament (id, name, type_genre) VALUES (288, N'Cachantun Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (289, N'Copa Colsanitas Santander', 2);
INSERT tournament (id, name, type_genre) VALUES (290, N'Canara Bank Bangalore Open', 2);
INSERT tournament (id, name, type_genre) VALUES (291, N'Zurich Open', 2);
INSERT tournament (id, name, type_genre) VALUES (292, N'Qatar Telecom German Open', 2);
INSERT tournament (id, name, type_genre) VALUES (293, N'DFS Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (294, N'Sunfeast Open', 2);
INSERT tournament (id, name, type_genre) VALUES (295, N'Guangzhou International Women''s Open', 2);
INSERT tournament (id, name, type_genre) VALUES (296, N'Hungarian Grand Prix', 2);
INSERT tournament (id, name, type_genre) VALUES (297, N'Southern California Open', 2);
INSERT tournament (id, name, type_genre) VALUES (298, N'East West Bank Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (299, N'Bausch & Lomb Championships', 2);
INSERT tournament (id, name, type_genre) VALUES (300, N'J&S Cup', 2);
INSERT tournament (id, name, type_genre) VALUES (301, N'Acura Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (302, N'Toronto', 2);
INSERT tournament (id, name, type_genre) VALUES (303, N'Forest Hills Sony Ericsson WTA Tour Classic', 2);

INSERT tournament (id, name, type_genre) VALUES (304, N'FesGrand Prix de SAR La Princesse Lalla Meryem', 2);
INSERT tournament (id, name, type_genre) VALUES (305, N'Forest Hills Tennis Classic', 2);
INSERT tournament (id, name, type_genre) VALUES (306, N'Japan Women''s Open Tennis', 2);
INSERT tournament (id, name, type_genre) VALUES (307, N'Garanti Koza WTA Tournament of Champions', 2);
INSERT tournament (id, name, type_genre) VALUES (308, N'Barcelona KIA', 2);
INSERT tournament (id, name, type_genre) VALUES (309, N'PTT Bangkok Open', 2);
INSERT tournament (id, name, type_genre) VALUES (310, N'Ladies Championship Gstaad', 2);
INSERT tournament (id, name, type_genre) VALUES (311, N'Korea Open', 2);